backend:
  name: git-gateway
  branch: vitesse
media_folder: 'public/images'
public_folder: '/images'
display_url: https://starlong-me.netlify.app
publish_mode: editorial_workflow
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'pages/posts'
    create: true
    slug: '{{slug}}'
    filter: { field: "layout" }
    preview_path: posts/{{slug}}
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '描述', name: 'description', widget: 'string', required: false }
      - { label: '横幅', name: 'image', widget: 'image', required: true }
      - { label: '时间', name: 'date', widget: 'datetime' }
      - { label: '主体', name: 'body', widget: 'markdown' }
